const rulesDatabase = {
  "rules": [
    { "code": "0.4", "variants": ["0.4", "fake admin", "фейк админ", "выдавать себя за админа"], "ban_time": "3d", "stackable": false },
    { "code": "0.6", "variants": ["0.6", "обман", "развод", "scam", "скам"], "ban_time": ["1w", "perma"], "stackable": false },
    { "code": "0.7", "variants": ["0.7", "обход наказания", "bypass ban", "обход бана", "обход мута"], "ban_time": "perma", "stackable": false },
    { "code": "0.8", "variants": ["0.8", "продажа валюты", "rmt", "РМТ"], "ban_time": "perma", "stackable": false },
    { "code": "0.9", "variants": ["0.9", "урон экономике", "краш экономики"], "ban_time": "perma", "stackable": false },
    { "code": "0.10", "variants": ["0.10", "продажа аккаунта", "передача аккаунта"], "ban_time": "perma", "stackable": false },
    { "code": "0.13", "variants": ["0.13"], "ban_time": "1h", "stackable": false },
    { "code": "0.15", "variants": ["0.15", "обман на разборке"], "ban_time": "3h", "stackable": false },
    { "code": "0.16", "variants": ["0.16", "спам"], "ban_time": "1d", "stackable": false },
    { "code": "0.18", "variants": ["0.18", "помеха работе администрации"], "ban_time": "1h", "stackable": false },
    { "code": "0.19", "variants": ["0.19", "провокация"], "ban_time": "1d", "stackable": false },
    { "code": "0.21", "variants": ["0.21", "слив игроков"], "ban_time": "1d", "stackable": false },
    { "code": "0.22", "variants": ["0.22", "читы", "софт"], "ban_time": "1d", "stackable": false },
    { "code": "0.23", "variants": ["0.23", "обход афк"], "ban_time": "1w", "stackable": false },
    { "code": "0.24", "variants": ["0.24", "/hobo", "/miner"], "ban_time": "1d", "stackable": false },
    { "code": "0.25", "variants": ["0.25", "запись обзвона"], "ban_time": "perma", "stackable": false },
    { "code": "0.27", "variants": ["0.27", "bouncy ball"], "ban_time": "1d", "stackable": false },
    { "code": "0.29", "variants": ["0.29", "пропы на аукционе"], "ban_time": "1d", "stackable": false },
    { "code": "0.30", "variants": ["0.30", "угрозы", "шантаж"], "ban_time": "perma", "stackable": false },
    { "code": "0.31", "variants": ["0.31", "доксинг"], "ban_time": "perma", "stackable": false },
    { "code": "1.1", "variants": ["1.1", "NonRP", "nonrp", "нонрп", "НонРП", "NRP", "nrp"], "ban_time": "10mi", "stackable": true },
    { "code": "1.2", "variants": ["1.2", "Leave", "leave", "лив", "ЛИВ", "LE", "le"], "ban_time": ["3h", "6h"], "stackable": false },
    { "code": "1.3", "variants": ["1.3", "LeaveRP", "leaverp", "ливрп", "ЛИВРП", "LRP", "lrp"], "ban_time": "30mi", "stackable": false },
    { "code": "1.4", "variants": ["1.4", "FreeDamage", "freedamage", "фридамаг", "ФРИДАМАГ", "FDMG", "fdmg"], "ban_time": "10mi", "stackable": true },
    { "code": "1.5", "variants": ["1.5", "FreeKill", "freekill", "фрикилл", "ФРИКИЛЛ", "FK", "fk"], "ban_time": "15mi", "stackable": true, "max_stack": 2 },
    { "code": "1.6", "variants": ["1.6", "RDM", "rdm", "рдм", "РДМ"], "ban_time": "10h", "stackable": false },
    { "code": "1.7", "variants": ["1.7", "MassRDM", "massrdm", "масс рдм", "MRDM", "mrdm"], "ban_time": ["1d", "1w"], "stackable": false },
    { "code": "1.8", "variants": ["1.8", "NewLifeRule", "newliferule", "нлр", "НЛР", "NLR", "nlr"], "ban_time": "10mi", "stackable": true },
    { "code": "1.9", "variants": ["1.9", "FearRP", "fearrp", "фирп", "ФИРП", "FRP", "frp"], "ban_time": "10mi", "stackable": true },
    { "code": "1.9.1", "variants": ["1.9.1", "Abuse", "abuse"], "ban_time": "20mi", "stackable": true },
    { "code": "1.10", "variants": ["1.10", "JobAbuse", "jobabuse", "джобабуз", "JA", "ja"], "ban_time": "20mi", "stackable": true },
    { "code": "1.11", "variants": ["1.11", "FreeArrest", "freearrest", "фриарест", "FA", "fa"], "ban_time": "30mi", "stackable": false },
    { "code": "1.11.1", "variants": ["1.11.1", "FreeUnArrest", "freeunarrest", "FUA", "fua"], "ban_time": "20mi", "stackable": false },
    { "code": "1.12", "variants": ["1.12", "MassFreeArrest", "massfreearrest", "масс фриарест", "MFA", "mfa"], "ban_time": ["3h", "10h"], "stackable": false },
    { "code": "1.13", "variants": ["1.13", "FreeWanted", "freewanted", "фривантед", "FWanted"], "ban_time": "10mi", "stackable": false },
    { "code": "1.14", "variants": ["1.14", "MassFreeWanted", "massfreewanted", "MFWanted"], "ban_time": "3h", "stackable": false },
    { "code": "1.15", "variants": ["1.15", "НПВ", "нпв"], "ban_time": "20mi", "stackable": false },
    { "code": "1.16", "variants": ["1.16", "CustomJob", "customjob", "кастом джоб", "CJ", "cj"], "ban_time": "20mi", "stackable": true },
    { "code": "1.17.1", "variants": ["1.17.1", "OSA", "osa", "оса", "ОСА", "оскорбление"], "ban_time": "20mi", "stackable": false },
    { "code": "1.17.2", "variants": ["1.17.2", "OSADM", "osadm", "осадм", "оскорбление админа"], "ban_time": "2h", "stackable": false },
    { "code": "1.17.3", "variants": ["1.17.3", "OSAR", "osar", "осар", "оскорбление родных"], "ban_time": ["1d","1w"], "stackable": false },
    { "code": "1.17.4", "variants": ["1.17.4", "OSS", "oss", "осс", "оскорбление сервера"], "ban_time": ["2w", "2mo"], "stackable": false },
    { "code": "1.20", "variants": ["1.20", "РМР", "рмр", "расизм", "нацизм"], "ban_time": ['3h','12h','1d','1w'], "stackable": false },
    { "code": "1.21", "variants": ["1.21", "FreeWarrant", "freewarrant", "фриварант", "FW", "fw"], "ban_time": "30mi", "stackable": true },
    { "code": "1.23", "variants": ["1.23", "SpawnArrest", "spawnarrest", "спавнарест", "SArrest"], "ban_time": "20mi", "stackable": true },
    { "code": "1.24", "variants": ["1.24", "SpawnAbuse", "spawnabuse", "спавнабуз", "SAbuse"], "ban_time": "30mi", "stackable": true },
    { "code": "1.25", "variants": ["1.25", "PassageAbuse", "passageabuse", "PA", "pa"], "ban_time": "10mi", "stackable": false },
    { "code": "1.26", "variants": ["1.26", "KillZone", "killzone", "KZ", "kz"], "ban_time": "10mi", "stackable": false },
    { "code": "1.27", "variants": ["1.27", "PowerGaming", "powergaming", "павергейминг", "PG", "pg"], "ban_time": "10mi", "stackable": true },
    { "code": "1.28", "variants": ["1.28", "HealAbuse", "healabuse", "хилабуз"], "ban_time": "15mi", "stackable": true },
    { "code": "1.29", "variants": ["1.29", "NickNameAbuse", "nicknameabuse", "NNA", "nna"], "ban_time": "10mi", "stackable": false },
    { "code": "1.30", "variants": ["1.30", "FreeCheck", "freecheck", "фричек", "FCheck"], "ban_time": "10mi", "stackable": true },
    { "code": "1.31", "variants": ["1.31", "FreeCuff", "freecuff", "фрикафф", "FCuff"], "ban_time": "10mi", "stackable": false },
    { "code": "1.32", "variants": ["1.32", "MassFreeCuff", "massfreecuff", "масс фрикафф", "MFCuff"], "ban_time": "2h", "stackable": false },
    { "code": "1.33", "variants": ["1.33", "FreeDemote", "freedemote", "FDemote"], "ban_time": "20mi", "stackable": false },
    { "code": "1.34", "variants": ["1.34", "MassFreeDemote", "massfreedemote", "MFDemote"], "ban_time": "3h", "stackable": false },
    { "code": "1.35", "variants": ["1.35", "Реклама", "реклама"], "ban_time": ["1w", "1mo", "perma"], "stackable": false },
    { "code": "1.36", "variants": ["1.36", "NonRPGun", "nonrpgun", "нонрп ган", "NRPGun"], "ban_time": "15mi", "stackable": true },
    { "code": "1.37", "variants": ["1.37", "BugAbuse", "bugabuse", "багабуз", "BA", "ba"], "ban_time": ["2h", "6h"], "stackable": true },
    { "code": "1.38", "variants": ["1.38", "Неадекват", "неадекват"], "ban_time": "3h", "stackable": false },
    { "code": "1.39", "variants": ["1.39", "FreeTazer", "freetazer", "фритазер", "FZ", "fz"], "ban_time": "15mi", "stackable": true },
    { "code": "1.40", "variants": ["1.40", "OrgNameAbuse", "orgnameabuse", "ONA", "ona"], "ban_time": "10mi", "stackable": false },
    { "code": "1.41", "variants": ["1.41", "Cheats", "cheats", "читы", "софт"], "ban_time": "perma", "stackable": false },
    { "code": "1.42", "variants": ["1.42", "ПКС", "пкс", "краш сервера"], "ban_time": "perma", "stackable": false },
    { "code": "1.44", "variants": ["1.44", "Помеха", "помеха"], "ban_time": "30mi", "stackable": false },
    { "code": "1.45", "variants": ["1.45", "NonRPKill", "nonrpkill", "NRPKill"], "ban_time": "30mi", "stackable": true },
    { "code": "1.48", "variants": ["1.48", "Рецидив", "рецидив"], "ban_time": "1w", "stackable": false },
    { "code": "1.48.1", "variants": ["1.48.1", "Многократный Рецидив", "многократный рецидив"], "ban_time": "2w", "stackable": false },
    { "code": "1.49", "variants": ["1.49", "NonRPRadio", "nonrpradio", "NRPR", "nrpr"], "ban_time": "15mi", "stackable": false },
    { "code": "1.50", "variants": ["1.50", "ArmedRP", "armedrp", "армедрп", "ARP", "arp"], "ban_time": "15mi", "stackable": true },
    { "code": "1.1.9", "variants": ["1.1.9", "помеха ивенту"], "ban_time": "3h", "stackable": false },
    { "code": "1.1.35", "variants": ["1.1.35", "помощь в побеге"], "ban_time": "1h", "stackable": false },
    { "code": "1.1.42", "variants": ["1.1.42", "езда за пределами дорог"], "ban_time": "10mi", "stackable": false },
    { "code": "1.1.45", "variants": ["1.1.45", "нарушение правил банды"], "ban_time": "1h", "stackable": false },
    { "code": "1.1.51", "variants": ["1.1.51", "использование видео"], "ban_time": "20mi", "stackable": false },
    { "code": "1.1.54", "variants": ["1.1.54", "паркур"], "ban_time": "30mi", "stackable": false },
    { "code": "1.1.55", "variants": ["1.1.55", "игнорирование FearRP"], "ban_time": "20mi", "stackable": true },
    { "code": "2.1", "variants": ["2.1", "MingeBuilding", "MINGEBUILDING", "MB", "mb"], "ban_time": "20mi", "stackable": true },
    { "code": "2.2", "variants": ["2.2", "PropBlock", "propblock", "пропблок", "PB", "pb"], "ban_time": "10mi", "stackable": true },
    { "code": "2.3", "variants": ["2.3", "PropSpam", "propspam", "пропспам", "PS", "ps"], "ban_time": "3h", "stackable": false },
    { "code": "2.4", "variants": ["2.4", "PropClimb", "propclimb", "PC", "pc"], "ban_time": "10mi", "stackable": true },
    { "code": "2.5", "variants": ["2.5", "PropSurf", "propsurf", "PS", "ps"], "ban_time": "30mi", "stackable": false },
    { "code": "2.6", "variants": ["2.6", "FadingDoorAbuse", "fadingdoorabuse", "фдабуз", "FDA", "fda"], "ban_time": "10mi", "stackable": false },
    { "code": "2.7", "variants": ["2.7", "KeypadAbuse", "keypadabuse", "кейпадабуз", "KA", "ka"], "ban_time": "10mi", "stackable": true },
    { "code": "2.8", "variants": ["2.8", "PropPush", "proppush"], "ban_time": "10mi", "stackable": false },
    { "code": "2.9", "variants": ["2.9", "TextScreenAbuse", "textscreenabuse", "TSA", "tsa"], "ban_time": "10mi", "stackable": false },
    { "code": "2.10", "variants": ["2.10", "BuildZoneAbuse", "buildzoneabuse", "BZA", "bza"], "ban_time": ["10mi", "20mi"], "stackable": false },
    { "code": "2.11", "variants": ["2.11", "PosterAbuse", "posterabuse", "Pab", "pab"], "ban_time": "12h", "stackable": true },
    { "code": "2.12", "variants": ["2.12", "LampAbuse", "lampabuse", "LPA", "lpa"], "ban_time": "1d", "stackable": false },
    { "code": "ADM1.3", "variants": ["ADM1.3", "adm1.3", "оскорбление игроков админом"], "ban_time": "3d", "stackable": true },
    { "code": "ADM1.4", "variants": ["ADM1.4", "adm1.4", "некорректная причина бана"], "ban_time": ["1d", "3d"], "stackable": true},
    { "code": "ADM1.5", "variants": ["ADM1.5", "adm1.5"], "ban_time": ["1d", "3d"], "stackable": true },
    { "code": "ADM1.6", "variants": ["ADM1.6", "adm1.6"], "ban_time": "1d", "stackable": true },
    { "code": "ADM1.8", "variants": ["ADM1.8", "adm1.8"], "ban_time": "1h", "stackable": true },
    { "code": "ADM1.12", "variants": ["ADM1.12", "adm1.12", "Admin Abuse", "adminabuse", "админабуз"], "ban_time": "3d", "stackable": true },
    { "code": "ADM1.12.1", "variants": ["ADM1.12.1", "adm1.12.1", "sliv", "слив админки", "слив"], "ban_time": "perma", "stackable": false },
    { "code": "ADM1.13", "variants": ["ADM1.13", "adm1.13"], "ban_time": "12h", "stackable": true },
    { "code": "ADM1.15", "variants": ["ADM1.15", "adm1.15"], "ban_time": "1d", "stackable": true },
    { "code": "ADM1.20", "variants": ["ADM1.20", "adm1.20", "Free ban", "freeban", "фрибан"], "ban_time": "1d", "stackable": true },
    { "code": "ADM1.21", "variants": ["ADM1.21", "adm1.21"], "ban_time": "1h", "stackable": true }
  ]
};

if (typeof module !== 'undefined') module.exports = rulesDatabase;
